<?php
$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
?>
<style>
.download-resource .download-expiration {
    font-size: small;
    font-style: italic;
}
</style>
<div class="meta-group download-resource">
    <h4><?php echo $translate('Stats on holdings and downloads'); ?></h4>
    <div class="value">
        <?php echo $escape(sprintf($translate('Exemplars: %s'), $stats['exemplars'] === -1 ? $translate('unlimited') : $stats['exemplars'])); ?>
    </div>
    <div class="value">
        <?php echo $escape(sprintf($translate('Downloaded: %s'), $stats['downloaded'])); ?>
    </div>
    <div class="value">
        <?php echo $escape(sprintf($translate('Holdings: %s'), $stats['holdings'])); ?>
    </div>
    <div class="value">
        <?php echo $escape(sprintf($translate('Available: %s'),
            $stats['available'] === -1 ? $translate('unlimited') : $stats['available']
        )); ?>
    </div>
    <div class="value">
        <?php echo $escape(sprintf($translate('Past downloaded: %s'), $stats['past-downloaded'])); ?>
    </div>
</div>
