<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \DownloadManager\Api\Representation\DownloadRepresentation[] $downloads
 * @var \DownloadManager\Api\Representation\DownloadRepresentation[] $resources
 * @var \Omeka\Form\ConfirmForm $formDeleteSelected
 * @var \Omeka\Form\ConfirmForm $formDeleteAll
 * @var \DownloadManager\Form\QuickSearchForm $formSearch
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$hyperlink = $this->plugin('hyperlink');
$this->htmlElement('body')->appendAttribute('class', 'downloads browse');

$userIsAllowedBatchDelete = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_delete');
$this->headLink()->appendStylesheet($this->assetUrl('css/download-manager-admin.css', 'DownloadManager'));
$this->headScript()->appendFile($this->assetUrl('js/download-manager-admin.js', 'DownloadManager'));

$sortHeadings = [
    [
        'label' => $translate('Created'),
        'value' => 'created',
    ],
    [
        'label' => $translate('User'),
        'value' => 'owner',
    ],
    [
        'label' => $translate('Site'),
        'value' => 'site',
    ],
    /*
    [
        'label' => $translate('Group'),
        'value' => 'group',
    ],
    */
    [
        'label' => $translate('Resource'),
        'value' => 'resource',
    ],
    /*
    [
        'label' => $translate('Title'),
        'value' => 'dcterms:title',
    ],
    */
    [
        'label' => $translate('Status'),
        'value' => 'status',
    ],
    [
        'label' => $translate('Expiration'),
        'value' => 'expire',
    ],
];
?>

<?php echo $this->pageTitle('', 1, $translate('Downloads')); ?>

<?php echo $this->downloadSearchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php // echo $hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?php echo $hyperlink($translate('Search'), '#', ['class' => 'search advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php /*
<div id="page-actions">
    <?php if ($this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'create')): ?>
    <?php echo $hyperlink($translate('Add new download'), $this->url(null, ['action' => 'add'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>
*/ ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($downloads): ?>
<?php
// Nothing is updatable or deletable currently.
$userIsAllowedBatchUpdate = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_update');
$userIsAllowedBatchDelete = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_delete');
?>
<form method="post" id="batch-form" class="disable-unsaved-warning">
    <div class="batch-inputs">
        <select class="batch-actions-select" name="batch_action" aria-label="<?php echo $translate('Batch actions'); ?>">
            <option value="default"><?php echo $translate('Batch actions'); ?></option>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <option value="update-selected" class="batch-selected" disabled><?php echo $translate('Edit selected'); ?></option>
            <option value="update-all"><?php echo $translate('Edit all'); ?></option>
            <?php endif; ?>
            <?php if ($userIsAllowedBatchDelete): ?>
            <option value="delete-selected" class="batch-selected" disabled><?php echo $translate('Delete selected'); ?></option>
            <option value="delete-all"><?php echo $translate('Delete all'); ?></option>
            <?php endif; ?>
        </select>
        <div class="batch-actions">
            <button type="button" class="default active" disabled><?php echo $translate('Go'); ?></button>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <input type="submit" class="update-selected" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit'], true)); ?>">
            <input type="submit" class="update-all" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit-all'], true)); ?>">
            <?php endif; ?>
            <input type="hidden" name="query" class="batch-query" value="<?php echo $escape(json_encode($this->params()->fromQuery())); ?>">
            <?php if ($userIsAllowedBatchDelete): ?>
            <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?php echo $translate('Go'); ?></a>
            <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?php echo $translate('Go'); ?></a>
            <?php endif; ?>
        </div>
    </div>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="select-all" aria-label="<?php echo $translate('Select all'); ?>">
                <?php echo $translate('Title'); ?>
            </th>
            <th><?php echo $translate('Reader'); ?></th>
            <th><?php echo $translate('Status'); ?></th>
            <th><?php echo $translate('Expiration'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($downloads as $download): ?>
        <?php // $userIsAllowedUpdate = $download->userIsAllowed('update'); ?>
        <?php // $userIsAllowedDelete = $download->userIsAllowed('delete'); ?>
        <?php
        if ($owner = $download->owner()) {
            $ownerText = $hyperlink(
                sprintf('%s (%s)', $owner->email(), $owner->name()),
                $this->url('admin/id', ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()])
                );
        } else {
            $ownerText = $translate('[no owner]');
        }
        ?>
        <tr>
            <td>
                <input type="checkbox" name="resource_ids[]" value="<?php echo $download->id(); ?>" aria-label="<?php echo $translate('Select download'); ?>">
                <?php echo $download->resource()->linkPretty(); ?>
                <?php /*
                <ul class="actions">
                    <?php if ($userIsAllowedUpdate): ?>
                    <li><?php echo $download->link('', 'edit', [
                        'class' => 'o-icon-edit',
                        'title' => $translate('Edit'),
                    ]); ?></li>
                    <?php endif; ?>
                    <?php if ($userIsAllowedDelete): ?>
                    <li><?php echo $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $download->url('delete-confirm'),
                        'class' => 'o-icon-delete sidebar-content',
                        'title' => $translate('Delete'),
                    ]); ?></li>
                    <?php endif; ?>
                    <li><?php echo $hyperlink('', '#', [
                        'data-sidebar-selector' => '#sidebar',
                        'data-sidebar-content-url' => $download->url('show-details'),
                        'class' => 'o-icon-more sidebar-content',
                        'title' => $translate('Details'),
                    ]); ?></li>
                </ul>
                */ ?>
            </td>
            <td><?php echo $ownerText; ?></td>
            <td><?php echo $escape($translate($download->status())); ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($download->expire())); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="sidebar" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php if ($userIsAllowedBatchDelete): ?>
<div id="sidebar-delete-selected" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete downloads'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete the selected downloads?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s downloads and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ); ?></p>
            <?php echo $this->form($this->formDeleteSelected); ?>
        </div>
    </div>
</div>
<div id="sidebar-delete-all" class="sidebar">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete downloads'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete all downloads on all pages of this result?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s downloads and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ); ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?php echo $translate('Are you sure?'); ?></label>
            <?php echo $this->form($this->formDeleteAll); ?>
        </div>
    </div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
    var confirmForm = $(this);
    if ('confirm-delete-all' === this.id) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input[name="resource_ids[]"]:checked:not(:disabled)').each(function() {
            confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
        });
    }
});
$('.delete-all').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-selected'));
});
$('.delete-selected').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-all'));
    var inputs = $('input[name="resource_ids[]"]');
    $('#delete-selected-count').text(inputs.filter(':checked').length);
});
$('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
    $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
});
</script>
<?php endif; ?>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Omeka could not find any downloaded resources.'); ?></p>
</div>

<?php endif; ?>

<div id="sidebar-search" class="sidebar search">
    <?php echo $hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-search-form" class="disable-unsaved-warning">
            <h3><?php echo $translate('Search downloads'); ?></h3>
            <?php echo $this->form($formSearch); ?>
        </div>
    </div>
</div>
