<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var array $result
 * @var \DownloadManager\Form\QuickSearchForm $formSearch
 */

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'downloads download-by-site browse');

$userIsAllowedBatchDelete = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_delete');
$this->headLink()->appendStylesheet($this->assetUrl('css/download-manager-admin.css', 'DownloadManager'));
$this->headScript()->appendFile($this->assetUrl('js/download-manager-admin.js', 'DownloadManager'));

$sortHeadings = [
    /*
    [
        'label' => $translate('Reader'),
        'value' => 'owner_email',
    ],
    */
    [
        'label' => $translate('Title'),
        'value' => 'title',
    ],
    [
        'label' => $translate('Past items'),
        'value' => 'past_items',
    ],
    [
        'label' => $translate('Holding items'),
        'value' => 'holding_items',
    ],
    [
        'label' => $translate('Downloaded items'),
        'value' => 'downloaded_items',
    ],
    [
        'label' => $translate('Total'),
        'value' => 'total',
    ],
    [
        'label' => $translate('Users'),
        'value' => 'users',
    ],
];
?>

<?php echo $this->pageTitle('', 1, $translate('Downloads by site')); ?>

<?php echo $this->downloadSearchFilters(); ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php // echo $this->hyperlink($translate('Advanced search'), $this->url(null, ['action' => 'search'], ['query' => $this->params()->fromQuery()], true), ['class' => 'advanced-search']); ?>
    <?php echo $this->hyperlink($translate('Search'), '#', ['class' => 'search advanced-search']); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>

<?php /*
<div id="page-actions">
    <?php if ($this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'create')): ?>
    <?php echo $this->hyperlink($translate('Add new download'), $this->url(null, ['action' => 'add'], true), ['class' => 'button']); ?>
    <?php endif; ?>
</div>
*/ ?>

<?php $this->trigger('view.browse.before'); ?>
<?php if ($result): ?>
<?php
// Nothing is updatable or deletable currently.
$userIsAllowedBatchUpdate = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_update');
$userIsAllowedBatchDelete = false && $this->userIsAllowed(\DownloadManager\Api\Adapter\DownloadAdapter::class, 'batch_delete');
?>
<form method="post" id="batch-form" class="disable-unsaved-warning">
    <div class="batch-inputs">
        <select class="batch-actions-select" name="batch_action" aria-label="<?php echo $translate('Batch actions'); ?>">
            <option value="default"><?php echo $translate('Batch actions'); ?></option>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <option value="update-selected" class="batch-selected" disabled><?php echo $translate('Edit selected'); ?></option>
            <option value="update-all"><?php echo $translate('Edit all'); ?></option>
            <?php endif; ?>
            <?php if ($userIsAllowedBatchDelete): ?>
            <option value="delete-selected" class="batch-selected" disabled><?php echo $translate('Delete selected'); ?></option>
            <option value="delete-all"><?php echo $translate('Delete all'); ?></option>
            <?php endif; ?>
        </select>
        <div class="batch-actions">
            <button type="button" class="default active" disabled><?php echo $translate('Go'); ?></button>
            <?php if ($userIsAllowedBatchUpdate): ?>
            <input type="submit" class="update-selected" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit'], true)); ?>">
            <input type="submit" class="update-all" value="<?php echo $translate('Go'); ?>" formaction="<?php echo $escape($this->url(null, ['action' => 'batch-edit-all'], true)); ?>">
            <?php endif; ?>
            <input type="hidden" name="query" class="batch-query" value="<?php echo $escape(json_encode($this->params()->fromQuery())); ?>">
            <?php if ($userIsAllowedBatchDelete): ?>
            <a class="delete button sidebar-content delete-selected" data-sidebar-selector="#sidebar-delete-selected"><?php echo $translate('Go'); ?></a>
            <a class="delete button sidebar-content delete-all" data-sidebar-selector="#sidebar-delete-all"><?php echo $translate('Go'); ?></a>
            <?php endif; ?>
        </div>
    </div>

<table class="tablesaw batch-edit" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th>
                <input type="checkbox" class="select-all" aria-label="<?php echo $translate('Select all'); ?>">
                <?php echo $translate('Title'); ?>
            </th>
            <th><?php echo $translate('Past items'); ?></th>
            <th><?php echo $translate('Holding items'); ?></th>
            <th><?php echo $translate('Downloaded items'); ?></th>
            <th><?php echo $translate('Total'); ?></th>
            <th><?php echo $translate('Users'); ?></th>
            <th><?php echo $translate('Items/Users'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($result as $row): ?>
        <?php $title = $row['title']; ?>
        <?php // $userIsAllowedUpdate = $title->userIsAllowed('update'); ?>
        <?php // $userIsAllowedDelete = $title->userIsAllowed('delete'); ?>
        <?php
        if ($title != null) {
            $ownerText = $this->hyperlink(
                sprintf('%s', $title),
                $this->url('admin/site/slug/action', ['action' => 'stats', 'site-slug' => $row['title']])
            );
        } else {
            $ownerText = $translate('[no title]');
        }
        ?>
        <tr>
            <td>
                <input type="checkbox" name="resource_ids[]" value="<?php echo $row['id']; ?>" aria-label="<?php echo $translate('Select title'); ?>">
                <?php echo $ownerText; ?>
            </td>
            <td><?php if ($row['past_items']) echo $row['past_items']; ?></td>
            <td><?php if ($row['holding_items']) echo $row['holding_items']; ?></td>
            <td><?php if ($row['downloaded_items']) echo $row['downloaded_items']; ?></td>
            <td><?php if ($row['total']) echo $row['total']; ?></td>
            <td><?php if ($row['users']) echo $row['users']; ?></td>
            <td><?php if ($row['users']) echo ceil($row['total']/$row['users']); ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>

</form>

<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<div id="sidebar" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content"></div>
</div>

<?php if ($userIsAllowedBatchDelete): ?>
<div id="sidebar-delete-selected" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete downloads'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete the selected downloads?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s downloads and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                '<strong><span id="delete-selected-count"></span></strong>'
            ); ?></p>
            <?php echo $this->form($this->formDeleteSelected); ?>
        </div>
    </div>
</div>
<div id="sidebar-delete-all" class="sidebar">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-confirm">
            <h3><?php echo $translate('Delete downloads'); ?></h3>
            <p><?php echo $translate('Are you sure you would like to delete all downloads on all pages of this result?'); ?></p>
            <p class="error"><?php echo sprintf(
                $translate('%s: this action will permanently delete %s downloads and cannot be undone.'),
                sprintf('<strong>%s</strong>', $translate('Warning')),
                sprintf('<strong>%s</strong>', number_format($this->pagination()->getPaginator()->getTotalCount()))
            ); ?></p>
            <label><input type="checkbox" name="confirm-delete-all-check"> <?php echo $translate('Are you sure?'); ?></label>
            <?php echo $this->form($this->formDeleteAll); ?>
        </div>
    </div>
</div>

<script>
// Complete the batch delete form after confirmation.
$('#confirm-delete-selected, #confirm-delete-all').on('submit', function(e) {
    var confirmForm = $(this);
    if ('confirm-delete-all' === this.id) {
        confirmForm.append($('.batch-query').clone());
    } else {
        $('#batch-form').find('input[name="resource_ids[]"]:checked:not(:disabled)').each(function() {
            confirmForm.append($(this).clone().prop('disabled', false).attr('type', 'hidden'));
        });
    }
});
$('.delete-all').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-selected'));
});
$('.delete-selected').on('click', function(e) {
    Omeka.closeSidebar($('#sidebar-delete-all'));
    var inputs = $('input[name="resource_ids[]"]');
    $('#delete-selected-count').text(inputs.filter(':checked').length);
});
$('#sidebar-delete-all').on('click', 'input[name="confirm-delete-all-check"]', function(e) {
    $('#confirm-delete-all input[type="submit"]').prop('disabled', this.checked ? false : true);
});
</script>
<?php endif; ?>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Omeka could not find any downloaded resources.'); ?></p>
</div>

<?php endif; ?>

<div id="sidebar-search" class="sidebar search">
    <?php echo $this->hyperlink('', '#', [
        'class' => 'sidebar-close o-icon-close',
        'title' => $translate('Close'),
    ]); ?>
    <div class="sidebar-content">
        <div id="sidebar-search-form" class="disable-unsaved-warning">
            <h3><?php echo $translate('Search downloads'); ?></h3>
            <?php echo $this->form($formSearch); ?>
        </div>
    </div>
</div>
