<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Api\Representation\JobRepresentation[] $jobs
 */

// Copy of Omeka application/view/omeka/admin/job/browse.phtml, with a link.
// This process is currently simpler because the controller changed in the config in Omeka 1.2.1.

$translate = $this->plugin('translate');
$escape = $this->plugin('escapeHtml');
$this->htmlElement('body')->appendAttribute('class', 'jobs browse');
$sortHeadings = [
    [
        'label' => $translate('ID'),
        'value' => 'id',
    ],
    [
        'label' => $translate('Class'),
        'value' => 'class',
    ],
    [
        'label' => $translate('Status'),
        'value' => 'status',
    ],
    [
        'label' => $translate('Owner'),
        'value' => 'owner',
    ],
];
?>

<?php echo $this->pageTitle($translate('Jobs')); ?>

<?php if (count($jobs)): ?>

<div class="browse-controls">
    <?php echo $this->pagination(); ?>
    <?php echo $this->sortSelector($sortHeadings); ?>
</div>
<?php $this->trigger('view.browse.before'); ?>
<table class="tablesaw" data-tablesaw-mode="stack">
    <thead>
        <tr>
            <th><?php echo $translate('Id / Params'); ?></th>
            <th><?php echo $translate('Date'); ?></th>
            <th><?php echo $translate('Class'); ?></th>
            <th><?php echo $translate('Status / Log'); ?></th>
            <th><?php echo $translate('Owner'); ?></th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($jobs as $job): ?>
        <?php
        if ($owner = $job->owner()) {
            $ownerText = $this->hyperlink($owner->email(), $this->url(
                'admin/id',
                ['controller' => 'user', 'action' => 'show', 'id' => $owner->id()]
            ));
        } else {
            $ownerText = $translate('[no owner]');
        }
        ?>
        <tr>
            <td><?php echo $job->link($escape($job->id())); ?></td>
            <td><?php echo $escape($this->i18n()->dateFormat($job->started(), null, \Omeka\View\Helper\i18n::DATE_FORMAT_SHORT)); ?></td>
            <td><?php echo $escape($job->jobClass()); ?></td>
            <td><?php if ($job->log()): ?>
            <?php echo $this->hyperlink($translate($job->statusLabel()), $this->url('admin/id', ['controller' => 'job', 'action' => 'log', 'id' => $job->id()]), ['target' => '_blank']); ?>
            <?php else: ?>
            <?php echo $escape($translate($job->statusLabel())); ?>
            <?php endif; ?>
            <?php $totalLogs = $this->api()->search('logs', ['job_id' => $job->id()])->getTotalResults()?>
            -
            <?php if ($totalLogs): ?>
            <?php echo $this->hyperlink(sprintf($translate('%d logs'), $totalLogs),
                $this->url('admin/log/default', [], ['query' => ['job_id' => $job->id()]])); ?>
            <?php else: ?>
            <?php echo $translate('[no log]'); ?>
            <?php endif; ?>
            </td>
            <td><?php echo $ownerText; ?></td>
        </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<?php $this->trigger('view.browse.after'); ?>
<div class="browse-controls">
    <?php echo $this->pagination(); ?>
</div>

<?php else: ?>

<div class="no-resources">
    <p><?php echo $translate('Omeka could not find any jobs.'); ?></p>
</div>

<?php endif; ?>


