<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \Omeka\Form\ForgotPasswordForm $form
 */

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'guest-user forgot-password');
$form->prepare();
?>
<h1><?php echo $translate('Forgot Password'); ?></h1>
<?php echo $this->messages(); ?>
<?php
echo $this->form()->openTag($form);
echo $this->formCollection($form, false);
?>
<button><?php echo $translate('Send an email to reset the password'); ?></button>
<?php echo $this->form()->closeTag(); ?>
