<?php
/**
 * @var \Zend\View\Renderer\PhpRenderer $this
 * @var \GuestUser\Form\PhoneForm $form
 */

$translate = $this->plugin('translate');
$this->htmlElement('body')->appendAttribute('class', 'guest-user account');
$form->prepare();
?>

<?php echo $this->messages(); ?>

<?php echo $this->pageTitle($translate('My phone number')); ?>

<?php echo $this->form()->openTag($form); ?>
<div id="page-actions">
    <button><?php echo $translate('Update'); ?></button>
</div>

<?php echo $this->formCollection($form, false); ?>
<?php $this->trigger('view.add.form.after'); ?>
<?php echo $this->form()->closeTag(); ?>

<?php $this->trigger('view.add.after'); ?>
