<?php
$escape = $this->plugin('escapeHtml');
$this->htmlElement('html')->setAttribute('lang', $this->lang());
$this->headMeta()->setCharset('utf-8');
$this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1');
$this->headTitle($this->setting('installation_title', 'Omeka S'))->setSeparator(' · ');
$this->headLink()->prependStylesheet($this->assetUrl('css/style.css'));
$this->headLink()->prependStylesheet($this->assetUrl('css/iconfonts.css', 'Omeka'));
$this->headLink()->prependStylesheet('//fonts.googleapis.com/css?family=Lora:400,400italic,700,700italic|Bitter:700');
$this->headScript()->prependFile($this->assetUrl('js/global.js', 'Omeka'));
$this->headScript()->prependFile($this->assetUrl('vendor/jquery/jquery.min.js', 'Omeka'));
$this->trigger('view.layout');
$userBar = $this->userBar();
?>

<?php echo $this->doctype(); ?>
<?php echo $this->htmlElement('html'); ?>
    <head>
        <?php echo $this->headMeta(); ?>
        <?php echo $this->headTitle(); ?>
        <?php echo $this->headLink(); ?>
        <?php echo $this->headStyle(); ?>
        <?php if ($this->themeSetting('accent_color') !== '' || $this->themeSetting('nav_color') !== ''): ?>
        <style>
            <?php if ($accentColor = $this->themeSetting('accent_color')): ?>
            a {
                color: <?php echo $accentColor; ?>
            }

            input[type="submit"]:hover,
            button:hover,
            .button:hover,
            .sub-menu a:hover,
            .site-page-pagination a:hover,
            a.advanced-search:hover {
                background-color: <?php echo $accentColor; ?>
            }
            <?php endif; ?>

            <?php if ($navColor = $this->themeSetting('nav_color')): ?>
            .oc-menu {
                background-color: <?php echo $navColor; ?>
            }
            <?php endif; ?>
        </style>
        <?php endif; ?>
        <?php echo $this->headScript(); ?>
    </head>

    <?php echo $this->htmlElement('body'); ?>
        <div id="oc-container" class="oc-container">
            <div class="oc-pusher">
                <?php echo $userBar; ?>
                <header role="banner">
                    <?php if ($this->themeSetting('logo')): ?>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><img src="<?php echo $this->themeSettingAssetUrl('logo'); ?>" title="Logo"></a>
                    <?php else: ?>
                    <a href="<?php echo $site->url(); ?>" class="site-title"><?php echo $this->pageTitle($site->title()); ?></a>
                    <?php endif; ?>
                    <?php echo $this->partial('common/search-form'); ?>
                    <div id="oc-trigger">
                        <button id="menu-button" class="o-icon-menu" data-effect="oc-push" aria-label="<?php echo $this->translate('Menu'); ?>"></button>
                    </div>
                    <nav id="menu" class="oc-menu oc-push" role="navigation">
                        <?php echo $site->publicNav()->menu()->renderMenu(); ?>
                    </nav>
                </header>

                <main class="oc-content" role="main">
                  <div class="oc-content-inner">
                    <div id="content" role="main">
                      <?php echo $this->content; ?>
                    </div>
                    <footer>
                        <?php if ($footerContent = $this->themeSetting('footer')): ?>
                        <?php echo $footerContent; ?>
                        <?php else: ?>
                            <?php echo $this->translate('Powered by Omeka S'); ?>
                        <?php endif; ?>
                    </footer>
                  </div>
                </main>
            </div>
        </div>
        <script type="text/javascript" src="<?php echo $this->assetUrl('js/offcanvas.js'); ?>"></script>
    </body>
</html>
